const coursesList=[
    {
        id:"65e605e1dd72028d4e05d754",
        name: "Osnove programiranja: C",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet reiciendis natus eum maxime iure ipsa debitis optio voluptate, nostrum similique.",
        range: "10-14",
        price: "4990",
        related:["programiranje" , "frontend" , "10-14, C, Osnove programiranja: C"],
        link:"kursevi/osnove-programiranja-C",
        image:"/images/kursevi/word.png",
        aktuelan: true,
        onSale:false,
    },
    {
        id:"65e61245dd72028d4e05d755",
        name: "Web Development: HTML && CSS",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet reiciendis natus eum maxime iure ipsa debitis optio voluptate, nostrum similique.",
        range: "10-14",
        price: "4990",
        related:["programiranje" , "frontend" , "10-14, html,Web Development: HTML && CSS"],
        link:"kursevi/web-development",
        image:"/images/kursevi/word.png",
        aktuelan: true,
        onSale:false,
    },
    {
        id:"65e6010f39e3036a65084c10",
        name: "Microsoft Word",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet reiciendis natus eum maxime iure ipsa debitis optio voluptate, nostrum similique.",
        range: "10-14",
        price: "4990",
        related:["programiranje" , "backend" , "10-14", "office","Microsoft Word"],
        link:"kursevi/word",
        image:"/images/kursevi/word.png",
        aktuelan: true,
        onSale:false,
    },
    {
        id:"65e60555dd72028d4e05d751",
        name: "Microsoft Powerpoint",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet reiciendis natus eum maxime iure ipsa debitis optio voluptate, nostrum similique.",
        range: "10-14",
        price: "4990",
        related:["programiranje" , "backend" , "10-14","office", "Microsoft Powerpoint"],
        link:"kursevi/powerpoint",
        image:"/images/kursevi/word.png",
        aktuelan: true,
        onSale:true,
    },
    {
        id:"65e605afdd72028d4e05d752",
        name: "Microsoft Excel",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet reiciendis natus eum maxime iure ipsa debitis optio voluptate, nostrum similique.",
        range: "10-14",
        price: "4990",
        related:["programiranje" , "backend" , "10-14","office", "Microsoft Excel"],
        link:"kursevi/excel",
        image:"/images/kursevi/word.png",
        aktuelan: true,
        onSale:false,
    },
    ]
    export default coursesList