import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import {AuthContextProvider} from "@/context/AuthContext"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ITnaTI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">  
      <body className={`bg ${inter.className}`}>
      <AuthContextProvider>
        <Nav/>
          {children}
        <Footer/>
        </AuthContextProvider>
      </body>  
    </html>
  )
}
